development:
  adapter: sqlite3
  database: my_db
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: test
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST